-- ========================================================
-- NUR SHAXMAT 100 - SUPABASE AVTO-YANGILANISH JADVALI
-- ========================================================
-- Ushbu SQL kodni Supabase boshqaruv panelidagi (Dashboard)
-- SQL Editor bo'limiga nusxalab, "Run" tugmasini bosing:
-- https://supabase.com/dashboard/project/wxurybelmkfdcxdcmkgd/sql

-- 1. Jadvalni yaratish (agar mavjud bo'lmasa)
CREATE TABLE IF NOT EXISTS public.app_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_code INT NOT NULL,
    version_name TEXT NOT NULL,
    title TEXT DEFAULT 'Yangi versiya mavjud!',
    release_notes TEXT,
    bundle_url TEXT,
    apk_url TEXT NOT NULL,
    is_mandatory BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Jadvalga o'qish huquqini ochish (Row Level Security - RLS)
ALTER TABLE public.app_updates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read app_updates" ON public.app_updates;
CREATE POLICY "Public read app_updates" 
ON public.app_updates 
FOR SELECT 
USING (true);

-- 3. Hozirgi eng so'nggi v1.0.2 versiyasini kiritish:
INSERT INTO public.app_updates (version_code, version_name, title, release_notes, bundle_url, apk_url, is_mandatory, is_active)
VALUES (
    3,
    '1.0.2',
    'Yangi Versiya Chiqdi! (v1.0.2)',
    '• 5 xil til qoʻshildi (Oʻzbekcha Lotin, Ўзбекча Кирилл, Русский, English, Qaraqalpaqsha)
• Sozlamalarga 4 xil tovush mavzulari va audio sinovchi qoʻshildi
• 1–100 raqamli koordinatalarni yoqish/oʻchirish kiritildi
• Jonli avto-yangilanish tizimi toʻliq ishga tushirildi',
    'https://files.catbox.moe/9b312n.zip',
    'https://files.catbox.moe/2ab7i9.apk',
    false,
    true
);